### ISSUE TITLE
canonical-kubernetes: failed to find some applications

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#3]
```
[adam:~/Projects/conjure] [conjure-dev] master ± conjure-up -d canonical-kubernetes aws
[info] Summoning canonical-kubernetes to aws
[info] Creating new juju model named 'ghoul', please wait.
[info] Running pre deployment tasks.
[info] Finished pre deploy task: Finished pre deploy tasks...
[info] Deploying easyrsa... 
[info] easyrsa deployed.
[info] Deploying elasticsearch... 
[info] elasticsearch deployed.
[info] Deploying etcd... 
[info] etcd deployed.
[info] Deploying filebeat... 
[info] filebeat deployed.
[info] Deploying flannel... 
[info] flannel deployed.
[info] Deploying kibana... 
[info] kibana deployed.
[info] Deploying kubeapi-load-balancer... 
[info] kubeapi-load-balancer deployed.
[info] Deploying kubernetes-master... 
[info] kubernetes-master deployed.
[info] Deploying kubernetes-worker... 
[info] kubernetes-worker deployed.
[info] Deploying topbeat... 
[info] topbeat deployed.
[info] Setting application relations
[error] Error deploying services: (ServerError(...), 'application "kubernetes-master" not found')
[error] Error deploying services: 1
Exception in worker
Traceback (most recent call last):
  File "/home/adam/Projects/conjure/conjureup/juju.py", line 438, in do_add_all
    params=params)
  File "/home/adam/Projects/conjure/macumba/v2.py", line 119, in _request
    'Params': params})
  File "/home/adam/Projects/conjure/macumba/v2.py", line 130, in call
    return self.receive(req_id, timeout)
  File "/home/adam/Projects/conjure/macumba/api.py", line 136, in receive
    raise ServerError(res['Error'], res)
macumba.errors.ServerError: (ServerError(...), 'application "kubernetes-master" not found')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/adam/Projects/conjure/conjureup/juju.py", line 33, in _decorator
    return f(*args, **kwargs)
  File "/home/adam/Projects/conjure/conjureup/juju.py", line 441, in do_add_all
    exc_cb(e)
  File "/home/adam/Projects/conjure/conjureup/controllers/deploy/tui.py", line 23, in __handle_exception
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/concurrent/futures/thread.py", line 66, in _worker
    work_item.run()
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/concurrent/futures/thread.py", line 57, in run
    self.future.set_exception(e)
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/concurrent/futures/_base.py", line 507, in set_exception
    self._invoke_callbacks()
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "/home/adam/Projects/conjure/conjureup/async.py", line 29, in cb
    exc_callback(e)
  File "/home/adam/Projects/conjure/conjureup/controllers/deploy/tui.py", line 23, in __handle_exception
    sys.exit(1)
SystemExit: 1
```

**Comment by battlemidget** [comment]
Here is the error from the api server:
```
machine-0: 09:09:20 DEBUG juju.resource.state adding pending resource "kubernetes" for application "kubernetes-worker" (ID: b8994464-2d94-4217-8f45-b02a39073424)
machine-0: 09:09:20 TRACE juju.apiserver -> [A4] user-admin@local {"RequestId":25,"Response":{"pending-ids":["b8994464-2d94-4217-8f45-b02a39073424"]}}
machine-0: 09:09:20 TRACE juju.apiserver <- [A4] user-admin@local {"RequestId":26,"Type":"Application","Version":1,"Request":"Deploy","Params":{"applications":[{"application":"kubernetes-worker","series":"","c
harm-url":"cs:~containers/kubernetes-worker-1","channel":"","num-units":3,"config-yaml":"","constraints":{},"resources":{"kubernetes":"b8994464-2d94-4217-8f45-b02a39073424"}}]}}
machine-0: 09:09:20 TRACE juju.apiserver.common server RPC error [{github.com/juju/juju/apiserver/application/application.go:193: } {github.com/juju/juju/state/state.go:984: cannot add application "kubernetes-
worker"} {github.com/juju/juju/state/state.go:984: series is empty}]
machine-0: 09:09:20 TRACE juju.apiserver -> [A4] user-admin@local {"RequestId":26,"Response":{"results":[{"error":{"message":"cannot add application \"kubernetes-worker\": series is empty","code":""}}]}}
```

Need to add series to our deploy since at some point in time the juju deploy api made this a requirement

**Comment by battlemidget** [comment]
We need to make sure bundles that do not have a series in their charm-url that we set the series item in our deploy call to that of the toplevel bundle series or to a series supported by the charm (that we capture through a charm api call)

**Comment by battlemidget** [comment]
This is a working patch but didn't know if there was a better way to handle this inside the `Service` class of bundle-placement:

```
diff --git a/conjureup/juju.py b/conjureup/juju.py
index d87d8de..4f8c58a 100644
--- a/conjureup/juju.py
+++ b/conjureup/juju.py
@@ -394,7 +394,9 @@ def deploy_service(service, msg_cb=None, exc_cb=None):
                 application_to_resource_map[resource['Name']] = pid
             service.resources = application_to_resource_map
 
-        app_params = {"applications": [service.as_deployargs()]}
+        deploy_args = service.as_deployargs()
+        deploy_args['series'] = app.metadata_controller.series
+        app_params = {"applications": [deploy_args]}
 
         app.log.debug("Deploying {}: {}".format(service, app_params))
```

**Comment by battlemidget** [comment]
Fixed
