### ISSUE TITLE
Conjure-up does not account for Xenial commissioned NIC names (enox)

### ISSUE THREAD

**Issue by canonical-cgregan** [conjure-up/spells#65]
Normally we hack the bundle, but in the case of conjure-up we are not able to (at least not without some hacking). Perhaps it could run a quick ifconfig to validate.

2017-04-17 21:41:08 INFO config-changed Cannot find device "eth1"
2017-04-17 21:41:08 INFO config-changed Traceback (most recent call last):
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/config-changed", line 359, in <module>
2017-04-17 21:41:08 INFO config-changed     hooks.execute(sys.argv)
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/core/hookenv.py", line 731, in execute
2017-04-17 21:41:08 INFO config-changed     self._hooks[hook_name]()
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1864, in wrapped_f
2017-04-17 21:41:08 INFO config-changed     restart_functions)
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/core/host.py", line 655, in restart_on_change_helper
2017-04-17 21:41:08 INFO config-changed     r = lambda_f()
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1863, in <lambda>
2017-04-17 21:41:08 INFO config-changed     (lambda: f(*args, **kwargs)), restart_map, stopstart,
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/hardening/harden.py", line 79, in _harden_inner2
2017-04-17 21:41:08 INFO config-changed     return f(*args, **kwargs)
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/config-changed", line 145, in config_changed
2017-04-17 21:41:08 INFO config-changed     configure_ovs()
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/neutron_utils.py", line 856, in configure_ovs
2017-04-17 21:41:08 INFO config-changed     add_bridge_port(br, port, promisc=True)
2017-04-17 21:41:08 INFO config-changed   File "/var/lib/juju/agents/unit-neutron-gateway-0/charm/hooks/charmhelpers/contrib/network/ovs/__init__.py", line 47, in add_bridge_port
2017-04-17 21:41:08 INFO config-changed     subprocess.check_call(["ip", "link", "set", port, "up"])
2017-04-17 21:41:08 INFO config-changed   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
2017-04-17 21:41:08 INFO config-changed     raise CalledProcessError(retcode, cmd)
2017-04-17 21:41:08 INFO config-changed subprocess.CalledProcessError: Command '['ip', 'link', 'set', u'eth1', 'up']' returned non-zero exit status 1
2017-04-17 21:41:08 ERROR juju.worker.uniter.operation runhook.go:107 hook "config-changed" failed: exit status 1
2017-04-17 21:41:08 DEBUG juju.worker.uniter.operation executor.go:84 lock released
2017-04-17 21:41:08 INFO juju.worker.uniter resolver.go:100 awaiting error resolution for "config-changed" hook
2017-04-17 21:41:08 DEBUG juju.worker.uniter agent.go:17 [AGENT-STATUS] error: hook failed: "config-changed"

**Comment by ryan-beisner** [comment]
We believe this is resolved, based on current testing.  If you find that is not the case, please re-open the issue.  Thank you.
